# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "daily"
# 确保扫描所有子目录（如果适用）
  # 注意：如果您的根 pom.xml 包含了所有依赖管理，通常不需要这个额外的配置
 # - package-ecosystem: "maven"
  #  directory: "/backend" 
  #  schedule:
   #   interval: "daily"
